Gemfile.lock

- [httparty](http://github.com/jnunemaker/httparty), [0.16.1...0.16.2](http://github.com/jnunemaker/httparty/compare/v0.16.1...v0.16.2) ([CHANGELOG](https://github.com/jnunemaker/httparty/blob/v0.16.2/Changelog.md))
--

Bundle Update on 2018-04-02

---

Gemfile.lock

- [dotenv](https://github.com/bkeepers/dotenv), [2.2.1...2.2.2](https://github.com/bkeepers/dotenv/compare/v2.2.1...v2.2.2) ([CHANGELOG](https://github.com/bkeepers/dotenv/blob/v2.2.2/Changelog.md))
--

Bundle Update on 2018-04-10

---

Gemfile.lock

- [sentry-raven](https://github.com/getsentry/raven-ruby), [2.7.2...2.7.3](https://github.com/getsentry/raven-ruby/compare/v2.7.2...v2.7.3) ([CHANGELOG](https://github.com/getsentry/raven-ruby/blob/v2.7.3/changelog.md))
--

Bundle Update on 2018-04-27

---

Gemfile.lock

- [webmock](http://github.com/bblimke/webmock), [3.3.0...3.4.1](http://github.com/bblimke/webmock/compare/v3.3.0...v3.4.1) ([CHANGELOG](https://github.com/bblimke/webmock/blob/v3.4.1/CHANGELOG.md))
--

Bundle Update on 2018-05-07

---

Gemfile.lock

- [octokit](https://github.com/octokit/octokit.rb), [4.8.0...4.9.0](https://github.com/octokit/octokit.rb/compare/v4.8.0...v4.9.0)
--

Bundle Update on 2018-05-09

---

Gemfile.lock

- [faraday](https://github.com/lostisland/faraday), [0.15.0...0.15.1](https://github.com/lostisland/faraday/compare/v0.15.0...v0.15.1) ([CHANGELOG](https://github.com/lostisland/faraday/blob/v0.15.1/CHANGELOG.md))
--

Bundle Update on 2018-05-11

---

Gemfile.lock

- [diffy](http://github.com/samg/diffy), [3.2.0...3.2.1](http://github.com/samg/diffy/compare/v3.2.0...v3.2.1) ([CHANGELOG](https://github.com/samg/diffy/blob/master/CHANGELOG))
--

Bundle Update on 2018-05-20

---

Gemfile.lock

- [faraday](https://github.com/lostisland/faraday), [0.15.1...0.15.2](https://github.com/lostisland/faraday/compare/v0.15.1...v0.15.2) ([CHANGELOG](https://github.com/lostisland/faraday/blob/v0.15.2/CHANGELOG.md))
--

Bundle Update on 2018-05-24

---

Gemfile.lock

- [webmock](http://github.com/bblimke/webmock), [3.4.1...3.4.2](http://github.com/bblimke/webmock/compare/v3.4.1...v3.4.2) ([CHANGELOG](https://github.com/bblimke/webmock/blob/v3.4.2/CHANGELOG.md))
--

Bundle Update on 2018-06-04

---

Gemfile.lock

- [sentry-raven](https://github.com/getsentry/raven-ruby), [2.7.3...2.7.4](https://github.com/getsentry/raven-ruby/compare/v2.7.3...v2.7.4) ([CHANGELOG](https://github.com/getsentry/raven-ruby/blob/v2.7.4/changelog.md))
--

Bundle Update on 2018-06-15

---

Gemfile.lock

- [dotenv](https://github.com/bkeepers/dotenv), [2.4.0...2.5.0](https://github.com/bkeepers/dotenv/compare/v2.4.0...v2.5.0) ([CHANGELOG](https://github.com/bkeepers/dotenv/blob/v2.5.0/Changelog.md))
--

Bundle Update on 2018-06-22

---

Gemfile.lock

- [rspec-expectations](http://github.com/rspec/rspec-expectations), [3.8.0...3.8.1](http://github.com/rspec/rspec-expectations/compare/v3.8.0...v3.8.1) ([CHANGELOG](https://github.com/rspec/rspec-expectations/blob/v3.8.1/Changelog.md))
--

Bundle Update on 2018-08-07

---

Gemfile.lock

- [public_suffix](http://github.com/weppos/publicsuffix-ruby), [3.0.2...3.0.3](http://github.com/weppos/publicsuffix-ruby/compare/v3.0.2...v3.0.3) ([CHANGELOG](https://github.com/weppos/publicsuffix-ruby/blob/v3.0.3/CHANGELOG.md))
--

Bundle Update on 2018-08-16

---

Gemfile.lock

- [octokit](https://github.com/octokit/octokit.rb), [4.10.0...4.11.0](https://github.com/octokit/octokit.rb/compare/v4.10.0...v4.11.0)
--

Bundle Update on 2018-08-31

---

Gemfile.lock

- [octokit](https://github.com/octokit/octokit.rb), [4.11.0...4.12.0](https://github.com/octokit/octokit.rb/compare/v4.11.0...v4.12.0)
--

Bundle Update on 2018-09-12

---

Gemfile.lock

- [rspec-expectations](http://github.com/rspec/rspec-expectations), [3.8.1...3.8.2](http://github.com/rspec/rspec-expectations/compare/v3.8.1...v3.8.2) ([CHANGELOG](https://github.com/rspec/rspec-expectations/blob/v3.8.2/Changelog.md))
--
Brought to you by [gem_dandy](https://github.com/SeeClickFix/gem_dandy) - Automated Dependency Updates

Bundle Update on 2018-10-10

---

Gemfile.lock

- [octokit](https://github.com/octokit/octokit.rb), [4.12.0...4.13.0](https://github.com/octokit/octokit.rb/compare/v4.12.0...v4.13.0)
--
Brought to you by [gem_dandy](https://github.com/SeeClickFix/gem_dandy) - Automated Dependency Updates

Bundle Update on 2018-10-12

---

Gemfile.lock

- [dotenv](https://github.com/bkeepers/dotenv), [2.5.0...2.6.0](https://github.com/bkeepers/dotenv/compare/v2.5.0...v2.6.0) ([CHANGELOG](https://github.com/bkeepers/dotenv/blob/master/Changelog.md))
--
Brought to you by [gem_dandy](https://github.com/SeeClickFix/gem_dandy) - Automated Dependency Updates

Bundle Update on 2019-01-06

---

.travis.yml
Gemfile
Gemfile.lock
lib/tasks/heroku.rake

Hello SCF friends! We've finally gotten around to implementing this awesome library in our apps! While working through the implementation I ran into a few snags. I've compiled the code changes I had to make into one PR since they were all relatively minor. If you only one to accept one, or a few, of the changes, I can gladly split them into separate PRs.
1. updated to ruby 2.5.3. Updating to `2.6.0` seemed a bit aggressive?
2. Allowed `dotenv` to load env vars in the `heroku:update` rake task. Running this command locally to verify it's working was challenging without dotenv doing the heavy lifting of loading all the env vars in .env automatically.
3. Added some logging output to `heroku:update`. When debugging our heroku automated setup, it was difficult to know why the system was …

A few installer usability improvements

---

Gemfile.lock

- [sentry-raven](https://github.com/getsentry/raven-ruby), [2.7.4...2.8.0](https://github.com/getsentry/raven-ruby/compare/v2.7.4...v2.8.0) ([CHANGELOG](https://github.com/getsentry/raven-ruby/blob/v2.8.0/changelog.md))
--
Brought to you by [gem_dandy](https://github.com/SeeClickFix/gem_dandy) - Automated Dependency Updates

Bundle Update on 2019-01-10
